### ISSUE TITLE
Use arrow keys to scroll inside stack and change series

### ISSUE THREAD

**Issue by pacssee** [nroduit/Weasis#235] opened 2021-12-29 08:11 UTC
Hi,
This is in relation to #204 which is closed.
This is a recurring ask from physicians who are using the software.
It would be beneficial to allow the user to choose whether the arrow keys are used within the context of the chosen tool (the current behavior) or used separately for scroll purposes (for example, right and left arrows - move between series, up and down arrows - scroll inside the stack). In many PACS systems this has become quite a common feature and users are expecting this.
Scrolling is a more intuitive function for the arrow keys while the graphic tools such as pan and zoom are usually accessed using the mouse.
Please consider.
Thank you so much for your continued excellent work.

**Comment by shlomgad** [comment] 2023-05-10 07:46
Hi, is this planned for the future ?
Browsing a study with the keyboard (moving between series and moving between images inside a series without requring a mouse) is supported in most PACS systems and is expected by radiologists as a basic feature.

**Comment by nroduit** [comment] 2023-05-11 07:35
Yes, a navigation toolbar is in the roadmap but not with high priority. To implement this request quickly, we need contributors.

**Comment by nroduit** [comment] 2023-11-11 07:39
Duplicate of https://github.com/nroduit/Weasis/issues/483

**Closed by nroduit** 2023-11-11 07:39 UTC
Labels: Type: Enhancement, Status: Duplicate
