### ISSUE TITLE
Weasis binaries does not launch in MacOS Mojave

### ISSUE THREAD

**Issue by ianholing** [nroduit/Weasis#85] opened 2019-05-27 09:59 UTC
**Weasis binaries does not launch in MacOS Mojave**
I'm aware there is some issues with Java 11 and gatekeeper, but I managed to install 1.8 and use it by editing /etc/profile and adding this:
* export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

I also change my gatekeeper options to allow everything and **the App continues closing itself a second after I run it with a double click**.
**Instead of that, you can perfectly run it if you try it with a terminal** using: ./viewer-mac.app/Contents/MacOS/viewer-mac.sh 

**To Reproduce**
1. Download the last weasis binaries: https://sourceforge.net/projects/dcm4che/files/Weasis/3.0.4/weasis-portable.zip/download
2. Uncompress and manage your Java 11 and gatekeeper issues if you have them.
3. Once all it's done try to launch the Application with a double click 

**Expected behavior**
Same behaviour in a dobleclick than running it from terminal with "./viewer-mac.app/Contents/MacOS/viewer-mac.sh". Just to not close itself.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4 (18E226)
 - Java Rutime: 1.8.0_211, x86_64
 - Weasis Version 3.0.4

**Comment by nroduit** [comment] 2019-05-27 20:46
There are many issues on Mac related to security evolutions. The next release will fix them, see this [post](https://groups.google.com/d/msg/dcm4che/N49I-tE_XOE/p-NSYAPnCgAJ).

Duplicate of https://github.com/nroduit/Weasis/issues/62

**Closed by nroduit** 2019-05-27 20:46 UTC
Labels: Status: Duplicate
