### ISSUE TITLE
Weasis shuts down immediately after launch

### ISSUE THREAD

**Issue by rlcolburn** [nroduit/Weasis#470] opened 2023-09-28 04:28 UTC
### Describe the bug. What happened?

Windows 11 home 22h2 2261.2283

installed weasis version 4.2.0 from the microsoft store
When i try to launch, it seems to do so before automatically closing a split second later (before any chance to even load files).

Additional detail: weasis launch logo shows, then the plug-ins loader/launch box appears to run, shows "completed 41 of 41 plug-ins", and the program itself launches as well (icon in the taskbar too) , then subsequently closes everything.

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Windows

### Relevant log output

```shell
it doesnt stay open long enough to retrieve the logfiles given these instructions (very possibly user error on following the instructions)
```

**Comment by nroduit** [comment] 2023-09-28 17:51
This problem cannot be reproduced. It is absolutely necessary to [provide the log files](https://weasis.org/en/tutorials/logging/index.html), which certainly contain the cause of the problem.

Have you tried reinstalling the application?

**Comment by Doxxie** [comment] 2023-09-28 18:23
I have the same problem on a MacBook running Mojave 10.14 (32 bit). Weasis was installed today using the latest version. When Weasis is launched, it crashes without showing any screen.

I am not familiar with locating and sending the log files, as requested of the Original Poster.

**Comment by julKali** [comment] 2023-09-29 09:42
Not sure if this is related, but I experience the same on Fedora 38, using flatpak.

`flatpak run io.github.nroduit.Weasis` produces the following output:

[weasis.log](https://github.com/nroduit/Weasis/files/12763232/weasis.log)

The problem seems to be something related to X11 and Wayland:

> java.awt.HeadlessException: 
> No X11 DISPLAY variable was set,
> or no headful library support was found,
> but this program performed an operation which requires it,

I found this issue: https://github.com/dbeaver/dbeaver/issues/21299
that is also very recent and could be related.

**Comment by nroduit** [comment] 2023-09-29 17:17
Please don't post new problems here, but open a new issue so that readers can follow up on a single topic.

@julKali See https://github.com/nroduit/Weasis/issues/449#issuecomment-1655036360, https://github.com/nroduit/Weasis/issues/462#issuecomment-1691661673 and https://github.com/nroduit/Weasis/issues/303#issuecomment-1689986225 

@Doxxie  Please take a look at the package specifications for download. There are no more updates for this system since 2019. The majority of libraries no longer offer 32-bit builds and this is also the case for Weasis.

![image](https://github.com/nroduit/Weasis/assets/993975/63b5ed88-7090-4203-886c-9ec7ab472dc6)

**Comment by rlcolburn** [comment] 2023-09-30 23:43
> This problem cannot be reproduced. It is absolutely necessary to [provide the log files](https://weasis.org/en/tutorials/logging/index.html), which certainly contain the cause of the problem.
> 
> Have you tried reinstalling the application?

The instructions provided for getting the logfiles appear to be steps to take within the app - which i'm not able to do beacuse it doesnt stay open long enough to do anything.  

I have tried reinstalling multiple times, both from microsoft store and from weasis site itself.

**Comment by nroduit** [comment] 2023-10-01 07:14
Be careful not to install both versions at the same time.

The log file is located in <user.home>/.weasis/log, where <user.home> is the path of the current user (e.g. C:\Users\user1).

**Comment by rlcolburn** [comment] 2023-10-01 07:20
[boot-0.0.log](https://github.com/nroduit/Weasis/files/12776596/boot-0.0.log)

Thanks. boot log attached.  note: did not install both at the same time.

**Comment by nroduit** [comment] 2023-10-01 14:49
According to the logs, the application starts up correctly. As the window is not visible, try manually activating the application log (default.log) by following these instructions:
1. Close the application (verify in Task Manager that no Weasis process is running)
2. Edit the text file "C:\Users\ryanl\.weasis\preferences\ryanl\default\weasis.properties"
3. Replace `org.apache.sling.commons.log.file.activate=false` with `org.apache.sling.commons.log.file.activate=true` and save it
4. Run again the application
5. Get the default.log file

**Comment by rlcolburn** [comment] 2023-10-02 06:48
i followed steps 1-4 and got the same behavior (it appears to start up, and once its done launching it immediately quits/disapears).  
step 5: default log file - [default.log](https://github.com/nroduit/Weasis/files/12780227/default.log)

**Comment by nroduit** [comment] 2023-10-05 06:39
According to the logs, the application starts up normally and does not crash. The application window should be visible.

Is there some kind of hidden screen or workspace management? I've never seen a similar situation.

Is there any other particular element? virtualization context, antivirus blocking the application...

**Comment by rlcolburn** [comment] 2023-10-13 06:45
It does open, and is visible as it loads and opens, but then when it seems to be done opening, <1s later, it disapears (with out any interaction from me, or any indication why).  I'm just as confused as you.

**Comment by nroduit** [comment] 2023-10-14 07:44
Has Weasis ever worked on this operating system?
Do you have or have you had several screens?

Please check the file <user.home>/.weasis/data/weasis-core/persistence.properties for properties starting with last.window or screen.

You can also try deleting the folder <user.home>/.weasis.

**Comment by nroduit** [comment] 2024-03-16 07:13
Due to the lack of recent activity, we are closing this issue for now. However, if you have any new information or updates related to this bug, please feel free to reopen it.

**Closed by nroduit** 2024-03-16 07:13 UTC
Labels: Type: Question
