### ISSUE TITLE
DICOM export incomplete - always missing random images

### ISSUE THREAD

**Issue by hallerwillem** [nroduit/Weasis#457] opened 2023-08-15 19:58 UTC
### Describe the bug. What happened?

Hi Weasis team, 
I hope Im not creating a double Report here. I was thinking weasis is the best dicom viewer for my cause as i dicovered a problem that spoils the fun a bit.
I recently discovered the very convenient CD import feature. This works flawless. 

After having imported all the needed files I export the files to a folder on my hard drive. Select the Export Dicom feature, select the desired images in the export tree, select "export & close" without altering the options, select the desired folder, done without any error message.

The result of this is not satisfying. The selected files never match the source files, the stacks are always incomplete. It doesnt matter what kind of radiological modality Im exporting. Plain X-Rays are missing the second plain, CT or MRI Scans are missing random images in the exported series. The series are not missing totally. 

If you repeat the export process the missing images may fill up (only in random pattern)

The only purpose in creating a github account was posting this question. When adding log files "comment becomes too long" and i cant post this. sorry

Thank you for help!! 

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Windows

**Comment by hallerwillem** [comment] 2023-08-17 09:34
Correction: The series are not complete. Attaching a log file
[default.log](https://github.com/nroduit/Weasis/files/12367633/default.log)

The logged export resulted in 6 Series with a total of 7 pictures (pictures missing in series as well) instead of the desired 14 series of plain x-rays with a total of 29 pictures

**Comment by nroduit** [comment] 2023-08-17 09:46
The error message says that there is no SOP Instance UID. Can you put the unlimited stacktrace like in the screenshot [here](https://weasis.org/en/tutorials/logging/), it might help to get maybe more information.
```
17.08.2023 11:26:51.064 *ERROR* [SwingWorker-pool-6-thread-1] org.weasis.dicom.explorer.LocalExport: Cannot export DICOM java.lang.IllegalArgumentException: Missing SOP Instance UID
	at org.dcm4che3.data.Attributes.createFileMetaInformation(Attributes.java:3256)
	at org.dcm4che3.data.Attributes.createFileMetaInformation(Attributes.java:3220)
	at org.dcm4che3.data.Attributes.createFileMetaInformation(Attributes.java:3207)
```

**Comment by hallerwillem** [comment] 2023-08-17 09:55
This is what i already did. Its just a absolutely fresh log. Will work a bit with it, force a few CDs an imported files through the export and repost the log.

**Comment by nroduit** [comment] 2023-08-17 10:18
Have you tried to import the CD from a folder, not from DICOMDIR  and then export?

**Comment by hallerwillem** [comment] 2023-08-17 10:37
Yes. Imported pictures via "CD Import" and "exported"/saved them. Also imported from local folders I manually copied from CDs to drive (the way Im doing it right now) to weasis and exported them to see if it works. It does not. Same results.

**Comment by nroduit** [comment] 2023-08-17 10:51
Could you check if the SOP Instance UID value exists in the files that are not exported? see https://weasis.org/en/tutorials/tags

**Comment by hallerwillem** [comment] 2023-08-17 11:11
<img width="397" alt="Screenshot 2023-08-17 130547" src="https://github.com/nroduit/Weasis/assets/142347309/a78bc035-4d26-48e6-9336-eb40348fa080">
<img width="287" alt="Screenshot 2023-08-17 130711" src="https://github.com/nroduit/Weasis/assets/142347309/cb7945bb-8d5a-473c-b6a9-79bc8158dd8d">
<img width="293" alt="Screenshot 2023-08-17 130810" src="https://github.com/nroduit/Weasis/assets/142347309/282a47d6-ed11-4c45-ae0e-54f2c394aced">
Checked on 3 different files that went missing after export. As far is I see it the value exists

**Comment by nroduit** [comment] 2023-08-17 12:31
Could you share a dataset because I cannot reproduce the issue?

**Comment by hallerwillem** [comment] 2023-08-17 15:09
Sorry, call me noob, but i dont really get that question. What kind of dataset. Will do whatever i can

**Comment by hallerwillem** [comment] 2023-08-17 15:13
If you mean a set of dicom images, i can only have a look if i find the old MRI scan of myself and see if it happens with that one too. I think it will, because it happens with every set of images so far

**Comment by nroduit** [comment] 2023-08-17 15:16
Yes, I need data to reproduce the problem. You can send me information to download images via my email.

**Comment by hallerwillem** [comment] 2023-08-17 20:52
I just tested my own mri scans and importing/exporting works flawless. No issue with these, so sharing them might be pointless. Unfortunately I cant share any other data due to mentioned names/lack of anonymisation. 
It did not work with any of the dicom CDs I imported/exported recently. Dont know how to help except to keep the log rolling. Any idea?

**Comment by nroduit** [comment] 2023-08-18 08:51
Unfortunately, I'm not going to investigate further without a procedure to reproduce the problem.

You can increase the stacktrace as described above (only 3 lines of error) but I'm not sure you will get more relevant information.
Otherwise, you can anonymize a CD, and share it.

**Comment by hallerwillem** [comment] 2023-09-11 19:38
Ok, it keeps happening. All imports I did today  were stripped of several images. Attached screenshots of the explorer. 
The one with lower image counts are made after importing cd with weasis, exporting cd with weasis, reopening export folder on drive.
The one with higher image counts are made after manually copying the study to harddrive and opening the copied folder.
Attached the rolling log. Not shure if there are more details.
Attached log aswell. 

could you please give a little guide to anonymize the original dicom files? Referring to weasis help only explains the "export view" option to anonymize which creates non dicom files. Ill see what i can do.

Another option: change to new version and see if it keeps on happening, Might this be better?

<img width="143" alt="Screenshot 2023-09-11 211917" src="https://github.com/nroduit/Weasis/assets/142347309/4f69c529-ee25-4167-9041-d18af5ff0a84">
<img width="131" alt="Screenshot 2023-09-11 212119" src="https://github.com/nroduit/Weasis/assets/142347309/315652b6-519a-4bec-adcb-d5097072fb2f">
[default.log](https://github.com/nroduit/Weasis/files/12579758/default.log)

**Comment by hallerwillem** [comment] 2023-09-11 19:41
[default.log](https://github.com/nroduit/Weasis/files/12579784/default.log)

**Comment by nroduit** [comment] 2023-09-20 05:53
From the message "Gerät ist nicht bereit", the problem seems to be that the CD is difficult to read. Give it a try:
* Check for corrupted files (clean the CD)
* Check the CD drive's health (update drivers)
* Try with another CD drive or computer

Some CDs are also extremely slow to read because the files are not physically ordered according to DICOMDIR.

**Comment by nroduit** [comment] 2023-10-22 07:42
This issue is closed as it does not concern Weasis. 
[An improvement ](https://github.com/nroduit/Weasis/issues/479)must be made to alert the user to the file reading problem.

**Closed by nroduit** 2023-10-22 07:42 UTC
Labels: Type: Question
