### ISSUE TITLE
Is it possible to adjust slice thickness in MPR

### ISSUE THREAD

**Issue by Sloganso** [nroduit/Weasis#215] opened 2021-10-16 08:18 UTC
Great Dicom viewer with versatile function and user friendly interface.

Is it possible to adjust the slice thickness in MPR view?

Have a good day!

**Comment by nroduit** [comment] 2021-10-16 10:01
No, it is not real 3D. The missing orientations are generated only with the information of the original pixels.

**Comment by nroduit** [comment] 2023-05-27 08:03
Duplicate of https://github.com/nroduit/Weasis/issues/390

**Closed by nroduit** 2023-05-27 08:03 UTC
Labels: Type: Question
