### ISSUE TITLE
"weasis" protocol handler: Opening multiple studies in same instance

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#243] opened 2022-02-15 12:40 UTC
Since I replaced the jnlp handler with the "weasis" protocol each study is opened on its own weasis window. The former behavior was one tab per study everything on the same window.

Is there a way to force the new versions to open all studies on the same window?, just as the older protocol handler did.

**Comment by nroduit** [comment] 2022-02-15 15:49
By default, it should not open a new Window. 

There are two exceptions, when:

1.  the user has changed (weasis.user)
2.  the hash of the config.properties and ext-config.properties has changed

This is what we expected if the application configuration has changed or if it is another user

**Comment by leonardorame** [comment] 2022-02-16 13:10
Mm, no. I deleted the .weasis folder to be sure and opened two studies again. Each study opens a new Weasis window.

Btw. I'm on Linux.

**Comment by nroduit** [comment] 2022-02-16 13:16
I can't reproduce this problem. When I open several exams from the [demo page](https://nroduit.github.io/en/demo/) I get the exams added in the current window.

Which Linux distribution and version is it?

**Comment by leonardorame** [comment] 2022-02-16 13:37
Did you try clicking more than one time on the "Launch" button?. In my case it opens one Weasis windows every time I click there.

**Comment by nroduit** [comment] 2022-02-16 15:44
Yes. Which Linux distribution and version is it?

And when you run `xdg-open weasis://` from several terminals.

**Comment by leonardorame** [comment] 2022-02-16 16:00
In fact that was using FreeBSD. But I'm testing that on Windows and it looks like it's working as expected.

**Comment by nroduit** [comment] 2022-02-17 09:39
This system is outside of the tested systems. Could you give the boot log which should give information about the singleton mechanism?

**Comment by nroduit** [comment] 2023-05-27 08:16
Please reopen this issue if it has not been resolved in the current version.

**Closed by nroduit** 2023-05-27 08:16 UTC
Labels: Type: Question
