### ISSUE TITLE
Weasis not loading any image with MacOS 

### ISSUE THREAD

**Issue by subhasishdash** [nroduit/Weasis#260] opened 2022-04-27 16:37 UTC
**Describe the bug**
Weasis not loading any image with MacOS latest Mojave

**To Reproduce**
1. Go to weasis web launcher
2. Click on any launch button
3. It will load the weasis on desktop on MacOS
4. See error : 
![weasis](https://user-images.githubusercontent.com/3872365/165572459-14947554-dfbb-45dc-87e1-c14443bd3b3b.PNG)

**Expected behavior**
It should load the examples from https://nroduit.github.io/en/getting-started/weasis-protocol/

**Desktop:**
 - OS: MacOS
 - Java Rutime: java 18
 - Weasis Version 4.0.0.rc

**Screenshots** 
![weasis](https://user-images.githubusercontent.com/3872365/165572459-14947554-dfbb-45dc-87e1-c14443bd3b3b.PNG)

**Traces**
[boot-0.0.log](https://github.com/nroduit/Weasis/files/8574558/boot-0.0.log)
[default.log](https://github.com/nroduit/Weasis/files/8574559/default.log)

27.04.2022 21:27:40.562 *ERROR* [SwingWorker-pool-3-thread-3] org.weasis.dicom.explorer.wado.LoadRemoteDicomManifest: Download failed org.weasis.dicom.explorer.wado.DownloadException: Error on loading the XML Manifest from: https://nroduit.github.io/samples/Lumbar/mf.xml
	at org.weasis.dicom.explorer.wado.DownloadManager.buildDicomSeriesFromXml(DownloadManager.java:372)
	at org.weasis.dicom.explorer.wado.LoadRemoteDicomManifest.downloadManifest(LoadRemoteDicomManifest.java:168)
	at org.weasis.dicom.explorer.wado.LoadRemoteDicomManifest.doInBackground(LoadRemoteDicomManifest.java:147)
	at org.weasis.dicom.explorer.wado.LoadRemoteDicomManifest.doInBackground(LoadRemoteDicomManifest.java:42)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by nroduit** [comment] 2022-04-28 12:45
Thanks for your feedback, but I can't reproduce this problem when trying on versions 10.15 and 12.1.

According to the error, it's like a root certificate for https is missing, I don't understand why.

Could you test on another computer ?

**Comment by subhasishdash** [comment] 2022-04-28 12:51
I added boot.logs for the OS details. Please check
***** Configuration *****
  Last running version = null
  Current version = 4.0.0-RC
  Application name = Weasis
  Application Source ID = 419B40DE
  Application Profile = default
  Application local codebase = /Applications/Weasis.app/Contents/app
  Application codebase URL = file:/Applications/Weasis.app/Contents/app
  Application configuration file = file:/Applications/Weasis.app/Contents/app/conf/config.properties
  Application extension configuration file = file:/Applications/Weasis.app/Contents/app/conf/ext-config.properties
  User = varunajay
  User home directory = /Users/varunajay/.weasis
  Resources path = /Applications/Weasis.app/Contents/app/resources
  Preferences directory = /Users/varunajay/.weasis/preferences/varunajay/default
  Look and Feel = org.weasis.launcher.FlatWeasisTheme
  Languages path = file:/Applications/Weasis.app/Contents/app/bundle-i18n/
  Languages available = en,ar,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,de,el,hu_HU,it,ja,ko,ms_MY,fa,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,si,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = macosx-x86-64
  HTTP user agent = Weasis/4.0.0-RC (Mac OS X; 10.14.2; x86_64; default; NATIVE)
  Operating system = Mac OS X 10.14.2 x86_64
  Java vendor = Eclipse Adoptium
  Java version = 18
  Java Path = /Applications/Weasis.app/Contents/runtime/Contents/Home
  Java max memory (less survivor space) = 2.0 GiB
***** End of Configuration *****
27.04.2022 09:46:49.903 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

27.04.2022 09:46:56.935 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.

We have a issue in this specific case only for the Mac OS X 10.14.2 x86_64.
Weasis loads properly on other PC's

I tried your examples from weasis web launcher page to avoid confusion about certificate.
Because the logs says something else and the prompt says something about certificate.

**Comment by nroduit** [comment] 2022-04-29 06:47
You can try to set the set log level at DEBUG in the weasis preferences dialog.

Adding `java-options=-Djavax.net.debug=all`in the weasis package (Weasis.cfg) should help to understand which certificate is missing and where it try to get it on the system.

**Comment by nroduit** [comment] 2023-05-27 08:19
Please reopen this issue if it has not been resolved in the current version.

**Closed by nroduit** 2023-05-27 08:19 UTC
Labels: Type: Question
