### ISSUE TITLE
Chinese display error in DICOM information

### ISSUE THREAD

**Issue by xiaoluGood** [nroduit/Weasis#324] opened 2022-08-19 02:24 UTC
hi
I compiled the weasis source code, and want to change the problem of Chinese display error.
I use $dciom: get - W http://...xml to load DICOM, I want to use patient info in XML to replace those Chinese error,
How can I modify the source code

**Comment by nroduit** [comment] 2022-08-19 05:37
Please explain first what the problem is because if it is a bad encoding it can come from the files that are loaded.

**Comment by nroduit** [comment] 2023-05-27 08:24
Please reopen this issue if it has not been resolved in the current version.

**Closed by nroduit** 2023-05-27 08:24 UTC
Labels: Type: Question
