### ISSUE TITLE
Print Dialog not come upfront when apply for print.

### ISSUE THREAD

**Issue by mbshingala28** [nroduit/Weasis#222] opened 2021-11-30 09:29 UTC
**Describe the bug**
In Dicom viewer, go to File and select Print > Print 2D Viewer Layout P. Submit UI and when submitting print dialog open but it goes backside of the viewer and not come upfront when we click on the taskbar.

**Expected behavior**
The print pop-up should display upfront by default.

**Desktop (please complete the following information):**
 - OS: Windows
 - Java Rutime: 8

**Screenshots**
https://user-images.githubusercontent.com/58248433/144021141-6863fe5d-6cd4-4228-9022-4f268605130c.mp4

**Comment by nroduit** [comment] 2021-12-02 13:27
Which version of JRE 8 and which system? Because this problem has already been reported on some versions of the JRE.

Is Weasis launched via Java Web Start?

Is this problem reproducible with [the official native release](https://nroduit.github.io/en/getting-started/)?

**Comment by nroduit** [comment] 2023-05-27 08:14
Please reopen this issue if it has not been resolved in the current version.

**Closed by nroduit** 2023-05-27 08:14 UTC
