### ISSUE TITLE
Not all series (images) are displayed

### ISSUE THREAD

**Issue by mariobilk** [nroduit/Weasis#310] opened 2022-07-18 07:26 UTC
Hello, I have the following problem with a patient CD.

Other data can be displayed without any problems.

- tested with Weasis versions 4.0.1 and 3.8.1 (Windows 10 and 11)

Method:

1. successful import of a DICOM cd (one person with several series)
2. successful export of the data to the Conquest DICOM server (version 1.5.0b)
3. successful search of the data just exported
4. unsuccessful import of the selected data

Result: Not all series (images) are displayed

example

Conquest DICOM server log:
`[CONQUESTSRV1] Number of Images to send: 2
[CONQUESTSRV1] Sending file : d:\portable\dicomserver150b\data\5555\1.2.826.0.1.3680043.2.135.738174.44841213.7.1656044014.281.11_0001_000001_16563108340001.dcm
[CONQUESTSRV1] Sending file : d:\portable\dicomserver150b\data\5555\1.2.826.0.1.3680043.2.135.738174.44841213.7.1656044014.343.13_0001_000001_16563108340000.dcm
[CONQUESTSRV1] C-Get (StudyRoot)
[CONQUESTSRV1] UPACS THREAD 4: ENDED AT: Mon Jul 18 08:51:30 2022
[CONQUESTSRV1] UPACS THREAD 4: TOTAL RUNNING TIME: 0 SECONDS`

Weasis log:
`18.07.2022 08:46:02.613 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
18.07.2022 08:46:02.680 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
18.07.2022 08:46:02.710 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=test, weasis.name=Weasis, weasis.version=4.0.1, weasis.config.hash=-119178520, weasis.path=C:\Users\test\.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/C:/Program%20Files/Weasis/app, weasis.pref.local.session=true, weasis.codebase.local=C:\Program Files\Weasis\app, felix.extended.config.properties=file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties, felix.config.properties=file:/C:/Program%20Files/Weasis/app/conf/config.properties, weasis.source.id=64D59807, weasis.profile=default, http.agent=Weasis/4.0.1 (Windows 11; 10.0; amd64; pf:default; rv:4.0.1) Java/18.0.1}
18.07.2022 08:46:02.739 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 55.012
18.07.2022 08:46:02.874 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = de
18.07.2022 08:46:02.874 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = de_DE
18.07.2022 08:46:02.874 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = TRACE
18.07.2022 08:46:02.874 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
18.07.2022 08:46:02.875 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
18.07.2022 08:46:02.875 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
18.07.2022 08:46:02.875 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
18.07.2022 08:46:02.875 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
18.07.2022 08:46:02.994 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = -1
18.07.2022 08:46:03.643 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
18.07.2022 08:46:03.643 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
18.07.2022 08:46:03.647 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 4.0.1
  Current version = 4.0.1
  Application name = Weasis
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/config.properties
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties
  User = test
  User home directory = C:\Users\test\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\test\.weasis\preferences\test\default
  Look and Feel = com.formdev.flatlaf.FlatIntelliJLaf
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = en,ar,bg_BG,bs_BA,cs,de,el,es,fa,fr,hr_HR,hu_HU,it,ja,ko,ms_MY,pl_PL,pt,pt_BR,ro,ru_RU,si,sk_SK,sr_RS,sv,tr,uk,vi,vi_VN,zh_CN,zh_TW
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/4.0.1 (Windows 11; 10.0; amd64; pf:default; rv:4.0.1) Java/18.0.1
  Operating system = Windows 11 10.0 amd64
  Java vendor = Eclipse Adoptium
  Java version = 18.0.1
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 7,8 GiB
***** End of Configuration *****
18.07.2022 08:46:03.649 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

18.07.2022 08:46:03.930 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-ui-i18n
18.07.2022 08:46:03.935 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-send-i18n
18.07.2022 08:46:03.940 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-viewer2d-i18n
18.07.2022 08:46:03.944 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-viewer2d-i18n
18.07.2022 08:46:03.948 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-au-i18n
18.07.2022 08:46:03.953 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-api-i18n
18.07.2022 08:46:03.957 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-sr-i18n
18.07.2022 08:46:03.962 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-qr-i18n
18.07.2022 08:46:03.965 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-explorer-i18n
18.07.2022 08:46:03.970 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-ui-i18n
18.07.2022 08:46:03.974 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-wave-i18n
18.07.2022 08:46:03.978 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-codec-i18n
18.07.2022 08:46:04.546 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
18.07.2022 08:46:29.808 *INFO* [Dicom Model-pool-8-thread-1] org.opencv.osgi: Successfully loaded OpenCV native library.`

Test with other software:
The data is successfully displayed with ORTHANC, RadiAnt DICOM Viewer (64-bit) and MicroDICOM DICOM viewer.
Both retrieval from the Conquest DICOM server and via the file explorer.

Thank you!

**Comment by nroduit** [comment] 2022-07-30 09:57
Duplicate of https://github.com/nroduit/Weasis/issues/318

**Closed by nroduit** 2022-07-30 09:57 UTC
Labels: Status: Duplicate
