### ISSUE TITLE
Measurement not showing Suddenly

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#434] opened 2023-07-10 13:29 UTC
### Describe the bug. What happened?

The issue I notices from older versions 3.0, suddenly measurement function will on work.
it will not resolved by reinstalling or installation higher version. This issue will resolve after deleting .weasis folder under user root file of windows. yesterday the same happened under mac pc user too. 
I have attached video for the same. Reference image for .weasis folder.

### What version of Weasis are you running?

In all version of Weasis

### On which system the problem occurs?

Windows, macOS

### Relevant log output

```shell
Image uploaded
```

### Additional contextual elements

https://github.com/nroduit/Weasis/assets/63642104/a84eabaa-8488-4c91-9642-d22dbbce25de

![Capture  weasis](https://github.com/nroduit/Weasis/assets/63642104/8509bd26-fc1c-4bc9-bdc1-00d096d9c9c9)
![Capture  weasis delete](https://github.com/nroduit/Weasis/assets/63642104/12510114-c61f-4aba-b814-08114c1bdccb)

**Comment by nroduit** [comment] 2023-07-11 07:17
Can you tell me if any changes have been made to the preferences or any other action that leads to this problem? because I can't reproduce it.

Are there any errors in the[ log files](https://weasis.org/en/tutorials/logging/)?

Can you provide the contents of the .weasis/preferences directory?

**Comment by arunjoshtech** [comment] 2023-07-12 05:47
I am trying to find out how to take this log from MAC PC. I will get it shortly.

**Comment by nroduit** [comment] 2023-07-20 15:54
Logs [must be activated](https://weasis.org/en/tutorials/logging/).

Can you please respond to the other requests?

**Comment by arunjoshtech** [comment] 2023-08-02 02:37
Logs Must be activated means? kindly advise what to share exactly. yesterday also i found the same issues with another doctor and have taken the log.
[boot-1.0.log](https://github.com/nroduit/Weasis/files/12235430/boot-1.0.log)

**Comment by nroduit** [comment] 2023-08-03 08:47
Please read carefully [the page referenced above,](https://weasis.org/en/tutorials/logging/) which explains how logs work and how to activate them (boot.log + default.log).

**Comment by nroduit** [comment] 2023-10-22 07:50
Please reopen this issue if it has not been resolved in the current version.

**Closed by nroduit** 2023-10-22 07:50 UTC
Labels: Type: Question
