### ISSUE TITLE
I really wanna change the crosshair, most of case in my work need to customize them. I need the bar (the plane) can go through 2 random point in MPR mode

### ISSUE THREAD

**Issue by dtbao196** [nroduit/Weasis#380] opened 2023-03-13 19:02 UTC
thanks for your amazing work, I just have an idea that depends on my work

**Comment by nroduit** [comment] 2023-03-16 07:04
If you mean rendering from an oblique MPR, then this feature is not available yet but is under development.

**Comment by dtbao196** [comment] 2023-03-18 14:33
![image](https://user-images.githubusercontent.com/127786299/226112515-a599efdf-c880-443b-aee0-919cbe11f63a.png)

**Comment by dtbao196** [comment] 2023-03-18 14:34
it would be better if i could customize it like this

**Comment by tp89-x** [comment] 2023-04-07 09:13
I`m waiting for this  as much as you @dtbao196 :)

**Comment by nroduit** [comment] 2023-05-27 08:41
Duplicate of https://github.com/nroduit/Weasis/issues/390

**Closed by nroduit** 2023-05-27 08:41 UTC
Labels: Type: Question
