### ISSUE TITLE
Cannot display ECG 2.5x4 in continuous time

### ISSUE THREAD

**Issue by peter-doggart** [nroduit/Weasis#315] opened 2022-07-28 12:17 UTC
**Is your feature request related to a problem? Please describe.**
I use Weasis for viewing ECG Dicom files. However, to me at least, weasis displays ECG incorrectly as it isn't displayed in constant time from left to right like a standard ECG print out. Unless I've missed some obvious configuration, which is entirely possible!? 

Weasis currently displays the first 2.5 seconds of each lead in the grid. However, on a real ECG print out the leads are normally displayed as:
Leads I, II, and III 0-2.5 seconds.
Leads aVR, aVL and aVF 2.5-5 seconds
Leads V1-3 5-7.5 seconds.
Leads V4-6 7.5-10 seconds. 

This means that when you plot 4x2.5 with rhythm, all the beats should line up with the rhythm strip. 

**Describe the solution you'd like**
I would like an option or a way to configure that the ECG display format treats the x-axis of the plot as time to allow me to recreate ECG standard print-outs from existing machines. 

**Describe alternatives you've considered**
N/A

**Additional context**
For diagnosis, it's really useful to be able to align the rhythm strip with the beats above in the search of p-waves and other subtle ECG features that isn't possible with the current timing.

**Comment by nroduit** [comment] 2022-08-01 19:38
Thank you for reporting this problem. Indeed there is a bug in the display of 2x5 and 4x2.5 zones.

Do not hesitate to reopen if the problem is not fully resolved (will be in 4.0.2 published very soon).

**Closed by nroduit** 2022-08-01 19:38 UTC
Labels: Type: Bug
