### ISSUE TITLE
Free/oblique MPR reconstructions

### ISSUE THREAD

**Issue by kffiatek** [nroduit/Weasis#202] opened 2021-07-17 09:30 UTC
I am a neurosurgeon and this DICOM Viewer is great, almost complete tool for non-radiologist users to plane and perform treatment.

The only missing feature is "true" MPR. You provide TRI-planar reconstructions and those work like a charm. But it is very often necessary to "see" the plane parallel to the i.e. vertebral bodies or a titanium screw. Having true multi planar reconstructions (sometimes called oblique) is something that could skyrocket usage of the program in medical society. This is even more useful than 3D reconstructions (which are obviously more spectacular).

Of course, we have paid workstations like GE or Osirix in the main workplace but there is often a lot of "casual" places where doctors must see some CT scans therefore having your alternative is really great.

The only open source program on the market having this feature is Horos for Mac and many people buy Macs just for this program.

Guys from https://github.com/greg-gajda/dicom-viewer used your MPR module and improved it to have true/oblique MPRs (or so they say). Maybe it could be incorporated into Wheasis too?

**Comment by nroduit** [comment] 2021-07-20 20:49
I did start a development for an oblique MPR but unfortunately did not find the time to finish it.

Also in our hospital, we have an oblique MPR and 3D rendering plugin for Weasis. This plugin requires a graphics card and unfortunately cannot be released publicly because it contains proprietary code.

**Comment by marlonramon** [comment] 2021-07-29 20:50
@nroduit can you share the comercial contact to adquire that pluguins?

**Comment by MarceloAraujo08** [comment] 2023-03-20 19:27
Poderia enviar o contato @nroduit , gostaria do plugin MPR Obliquo. Dificil encontrar desenvolvedor para tals.

**Comment by nroduit** [comment] 2023-05-27 07:58
Duplicate of https://github.com/nroduit/Weasis/issues/390

**Closed by nroduit** 2023-05-27 07:58 UTC
Labels: Type: Question

**Comment by leon1227** [comment] 2023-10-09 12:41
> I did start a development for an oblique MPR but unfortunately did not find the time to finish it.
> 
> Also in our hospital, we have an oblique MPR and 3D rendering plugin for Weasis. This plugin requires a graphics card and unfortunately cannot be released publicly because it contains proprietary code.

Just saw this... it sounds great to have oblique MPR in this already nice Weasis application. Is it a commercial plugin? Could we contact or buy that?
